#!/bin/bash

basename="`basename "$1"`"
updatename="`echo $1 | sed -e 's/\.msi$//' `".update.txt
version="$2"
buildType="$3"
description="$4"
url="$5"

cat <<EOF
[$version]
Name=openSCADA Admin Client - $version
URL=http://download.openscada.org/installer/ostc/${buildType}/ostc_${version}_win32.win32.x86.msi
Size=`stat -c "%s" "$1"`
ReleaseDate=`date -r "$1" +%d/%m/%Y`
MD5=`md5sum "$1" | sed -e 's/ .*$//'`
ServerFileName=$basename
Flags=SilentInstall
AutoCloseApplication=[APPDIR]ostc.exe
RegistryKey=HKLM\\SOFTWARE\\TH4 SYSTEMS GmbH\\${version}\\Version
Version=${version}
Replaces=All
EOF