#!/bin/bash

set -e

. profile

pushd workspace

mvn org.apache.maven.plugins:maven-dependency-plugin:2.8:get \
        -Dartifact=org.eclipse.scada.releng:build-helper:${buildHelperVersion} \
        -DremoteRepositories=https://repo.eclipse.org/content/repositories/eclipsescada-releases

mvn org.eclipse.scada.releng:build-helper:${buildHelperVersion}:set-version \
	-U -llr \
	-Dpackagings=pom \
	-Dpoms=org.openscada.builder/aggregator/pom.xml,org.openscada.builder/superParent/pom.xml \
	-DnewVersion=$release

popd

