#!/bin/bash

set -e

. profile

pushd workspace/org.openscada.builder

echo "Build profile: $buildProfile"

pushd superParent
mvn clean deploy -P$buildProfile
popd

pushd aggregator
mvn clean deploy -P$buildProfile
popd


popd
